### ISSUE TITLE
Multi search URL can't be copied and reused

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs-ui#13]
If I do a multi search for:
```
drChaAngu
icAgrMuri
icPelCaes
idPhaPall
idTipVern
ihNabLimb
ihPleMinu
iiLimLuna
ioIscEleg
ipBraRisi
```
then I get the results as expected. However, then when I try to copy that URL, I get this:
```
https://goat.genomehubs.org/search?query=drChaAnguicAgrMuriicPelCaesidPhaPallidTipVernihNabLimbihPleMinuiiLimLunaioIscElegipBraRisi&result=taxon&includeEstimates=true&summaryValues=count#drChaAnguicAgrMuriicPelCaesidPhaPallidTipVernihNabLimbihPleMinuiiLimLunaioIscElegipBraRisi
```
which seems to remove the new lines from in between the names, so can't be reused

**Comment by rjchallis** [comment]
That's curious, when I copy the list from above and paste it into GoaT, I get a url with the newlines preserved on Chrome, Firefox and Safari:

```
https://goat.genomehubs.org/search?query=drChaAngu%0AicAgrMuri%0AicPelCaes%0AidPhaPall%0AidTipVern%0AihNabLimb%0AihPleMinu%0AiiLimLuna%0AioIscEleg%0AipBraRisi&result=taxon&includeEstimates=true&summaryValues=count#drChaAngu%0AicAgrMuri%0AicPelCaes%0AidPhaPall%0AidTipVern%0AihNabLimb%0AihPleMinu%0AiiLimLuna%0AioIscEleg%0AipBraRisi
```

Where are you copying this from? (wondering if a spreadsheet source may be introducing different newline characters)

**Comment by sujaikumar** [comment]
Sorry! Ignore me. It seems to be a browser specific issue (Vivaldi, with possibly too many javascript/other restrictions). Worked fine on Chrome and Safari just now. I should have checked that first.
