### ISSUE TITLE
Default index for multi search should be taxon

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs-ui#15]
In a multi-query search like [this](https://goat.genomehubs.org/search?query=Chrysochloris%20asiatica%0ARhynchocyon%20cirnei%0AMicrogale%20mergulus%0AAmblysomus%20hottentotus%0AAnomalurus%20beecrofti%0APedetes%20capensis%0ALeptosomus%20discolor%0AArdea%20goliath%0AColius%20striatus%0AAnhinga%20rufa%0AMicrocarbo%20africanus%0ACaprimulgus%20poliocephalus%0AMesitornis%20unicolor%0ATrionyx%20triunguis%0ARhinotyphlops%20boylei%0AChamaeleo%20africanus%0APelusios%20castaneus%0AOpidion%20barbatum%0ALatimeria%20chalumnae&result=multi&includeEstimates=true&summaryValues=count&taxonomy=ncbi#Chrysochloris%20asiatica%0ARhynchocyon%20cirnei%0AMicrogale%20mergulus%0AAmblysomus%20hottentotus%0AAnomalurus%20beecrofti%0APedetes%20capensis%0ALeptosomus%20discolor%0AArdea%20goliath%0AColius%20striatus%0AAnhinga%20rufa%0AMicrocarbo%20africanus%0ACaprimulgus%20poliocephalus%0AMesitornis%20unicolor%0ATrionyx%20triunguis%0ARhinotyphlops%20boylei%0AChamaeleo%20africanus%0APelusios%20castaneus%0AOpidion%20barbatum%0ALatimeria%20chalumnae), the default search index should be Taxon (currently it is multi)

**Comment by rjchallis** [comment]
should be fixed already in develop branch

**Comment by sujaikumar** [comment]
Thank you! I should have checked first! Will pull change right now...

**Comment by sujaikumar** [comment]
Works perfectly!
